version: '3'

services:
    web:
        container_name: exo_web
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./docker/php/httpd-vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/dxdebug.ini
        environment:
            PHP_IDE_CONFIG: serverName=test.exo-dev-local.com
        depends_on:
            - mysql
        networks:
            - default
        expose:
            - "9000"
            - "9001"

    mysql:
        container_name: exo_mysql
        image: mysql:5.7.24
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: exo_dev
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./docker/mysql/mysqld.cnf:/etc/mysql/conf.d/mysql.cnf:cached
            - ./docker/mysql/mysqld.cnf:/etc/mysql/mysql.cnf:cached
            - ./docker/mysql/mysqld.cnf:/etc/my.cnf:cached
        networks:
            - default

    phpmyadmin:
        container_name: exo_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=mysql
        depends_on:
            - mysql
        networks:
            - default

    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025 # smtp server
            - 8025:8025 # web ui
